name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, deploy
        run: |
          yarn
          yarn build
          npm publish
        env:
          CI: true
      - name: Tag
        uses: actions/bin/filter@master
        with:
          args: tag
      - name: Publish
        uses: actions/npm@master
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          args: publish
